name: vizzhy
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage:
  get: ^4.6.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  logger: ^2.4.0
  overlay_support: ^2.1.0
  terra_flutter_bridge: ^0.7.2
  webview_flutter: ^4.8.0
  path_provider: ^2.1.4
  syncfusion_flutter_pdfviewer: ^26.2.7
  file_picker: ^8.0.0+1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  sembast: ^3.7.2
  syncfusion_flutter_datepicker: ^26.2.7
  speech_to_text: ^6.6.2
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  lottie: ^3.1.2
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
  timezone: ^0.9.4
  flutter_timezone: ^3.0.0
  pinput: ^5.0.0
  easy_date_timeline: ^1.1.3
  package_info_plus: ^8.0.2

  path: any
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  permission_handler: ^11.3.1
  device_info_plus: any
  http: any
  flutter_dotenv: ^5.2.1
  chat_gpt_sdk: ^3.1.2
  flutter_markdown: ^0.7.4+1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_typeahead: ^5.2.0
  group_button: ^5.3.4
  dropdown_button2: ^2.3.9
  change_case: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

  #Code generator
  # envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  flutter_flavorizr: ^2.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/Icons/
    - assets/images/tryterra/
    - assets/images/profile/
    - assets/images/reports/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/Sf_Pro_Regular.otf
          weight: 400
        - asset: assets/fonts/Sf_Pro_Medium.otf
          weight: 500
        - asset: assets/fonts/Sf_Pro_Bold.otf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito_Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito_Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito_Regular.ttf
          weight: 400
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_Medium.ttf
          weight: 500

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
