// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcHkujQfywzy_PvOK2PAqi9IFiZmObk4',
    appId: '1:161045405457:web:11e3783883e4dc92b9f6b0',
    messagingSenderId: '161045405457',
    projectId: 'vizzhydev-2a71b',
    authDomain: 'vizzhydev-2a71b.firebaseapp.com',
    storageBucket: 'vizzhydev-2a71b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDc8sm3gF9ZOXl0AE5ltDIaQRfaoWUpk',
    appId: '1:161045405457:android:79c3045ed8864289b9f6b0',
    messagingSenderId: '161045405457',
    projectId: 'vizzhydev-2a71b',
    storageBucket: 'vizzhydev-2a71b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2z5zhF9Kya7M1z2sBzxIjJLSwjzL8Y3k',
    appId: '1:161045405457:ios:08952c4e56254288b9f6b0',
    messagingSenderId: '161045405457',
    projectId: 'vizzhydev-2a71b',
    storageBucket: 'vizzhydev-2a71b.appspot.com',
    iosBundleId: 'com.vizzhy.iottest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2z5zhF9Kya7M1z2sBzxIjJLSwjzL8Y3k',
    appId: '1:161045405457:ios:2d72a1af05acb49ab9f6b0',
    messagingSenderId: '161045405457',
    projectId: 'vizzhydev-2a71b',
    storageBucket: 'vizzhydev-2a71b.appspot.com',
    iosBundleId: 'come.vizzhy.vizzhy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQcHkujQfywzy_PvOK2PAqi9IFiZmObk4',
    appId: '1:161045405457:web:91019ce9d8d99996b9f6b0',
    messagingSenderId: '161045405457',
    projectId: 'vizzhydev-2a71b',
    authDomain: 'vizzhydev-2a71b.firebaseapp.com',
    storageBucket: 'vizzhydev-2a71b.appspot.com',
  );
}
